---
env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  project: ./tsconfig.json
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  "@typescript-eslint/ban-types":
    - error
  "@typescript-eslint/no-empty-function":
    - error
  "@typescript-eslint/no-empty-interface":
    - error
  "@typescript-eslint/no-explicit-any":
    - "off"
  "@typescript-eslint/no-inferrable-types":
    - "off"
  "@typescript-eslint/no-namespace":
    - "off"
  "@typescript-eslint/no-unused-vars":
    - "off"
  "@typescript-eslint/no-var-requires":
    - "off"
  brace-style:
    - "off"
    - 1tbs
    - allowSingleLine: true
  camelcase:
    - "off"
  comma-style:
    - error
  curly:
    - "off"
    - multi-line
    - consistent
  eqeqeq:
    - error
  indent:
    - error
    - 2
    - SwitchCase: 1
  no-case-declarations:
    - "off"
  no-console:
    - "off"
  no-constant-condition:
    - error
    - checkLoops: false
  no-control-regex:
    - "off"
  no-duplicate-imports:
    - error
    - includeExports: true
  no-empty:
    - error
  no-extra-parens:
    - "off"
    - all
  no-fallthrough:
    - error
  no-inline-comments:
    - "off"
  no-irregular-whitespace:
    - error
  no-multiple-empty-lines:
    - error
  no-trailing-spaces:
    - error
  no-undef:
    - "off"
  no-unused-vars:
    - "off"
  no-use-before-define:
    - "off"
  no-useless-catch:
    - "off"
  no-useless-concat:
    - error
  no-useless-escape:
    - error
  no-var:
    - error
  padded-blocks:
    - "off"
  prefer-const:
    - error
  prefer-template:
    - error
  quotes:
    - error
    - single
  semi:
    - error
    - always
  space-before-function-paren:
    - "off"
  template-curly-spacing:
    - error
  yoda:
    - error
